{% set name = "pure-sasl" %}
{% set version = "0.6.1" %}
{% set sha256 = "54458deb9574e293aa58d820f4a94271770401409c4cd8b3dd86f1a827cffde7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-dependencies --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - puresasl

about:
  home: https://github.com/thobbs/pure-sasl
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/thobbs/pure-sasl
  doc_url: https://github.com/thobbs/pure-sasl
  summary: A pure python SASL client

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
