travis:
  secure:
    BINSTAR_TOKEN: QZSgAuZf5O/GC6vGFG7P7EoDUaH6rW93twPnhooaPBgWKmuRLFb/vqbXXX2J4PY8MV52SyKaxUf0Bkow8E95SeBSMGC0fb0J1s5hPcOt92sLJDBUF8rPvnihKknvEQg8iKjz2cRl5ZYqpz1WRsi2cSorqIz4A/fcs+wzQ6tWGM8tarKuxvcrIJOmfYC20UZ9O5sjnfKhq9PKY3aNkT+i17sSRqJLlnimzFSxA4TRsgG3ui7mK/kk0gWd8zuqv+NzuzvU3gkai6y3W3jVfy1UbGBSceN+gD94GYX4rpYOTPYI3ujimWsH/v6yLBVU+Mapxqixz5qLhlVevPM48SOG5QIaQD/DnHnUyyWtflzcsW6lU6c1/97seCfl+owFh6gUJ0jfHHpalSsYTWMW7zo69OH4H7D5ebqH5RfXtJmudnawuoU2NbnPWQwQDef7qZsl9mYc0DrgPUh2eIzFdR00nnSbCBvDPiYs6q8IlKhUHwHv5tP3/15AZLOC8K2R5sJX+GpOHrMMMBra3uPI7ZstdUr0oWlGlX70eUGor9wPGKtEUxAtRHY5YL2JtGHHwa5eMTYM4FYMNoXw6aNsqiORzsRtf8NaXcyHAIUDuQ0/yTXIVzkMHr4Se+YEtDgoqZHSIojL0ophIf8Gw+6wNq6jJfP7NKeQlKeg6YkCMPJCVt0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
